Running suite(s): Default
18%: Checks: 11, Failures: 8, Errors: 1
public.c:15:F:Public:C_expr_2regs:0: Assertion 'run_expression("1+2+3+4") == 10' failed: run_expression("1+2+3+4") == -9999, 10 == 10
public.c:16:F:Public:C_expr_3regs:0: Assertion 'run_expression("(1+2)+(3+4)") == 10' failed: run_expression("(1+2)+(3+4)") == -9999, 10 == 10
public.c:18:F:Public:C_assign:0: Assertion 'run_program("def int main() { " "  int a; a = 2 + 3 * 4; " "  return a; }") == 14' failed: run_program("def int main() { " "  int a; a = 2 + 3 * 4; " "  return a; }") == -9999, 14 == 14
public.c:23:F:Public:C_assign_multiple:0: Assertion 'run_program("def int main() { " "  int a;" "  a = 2 + 3 * 4; " "  a = a - 4 / 2; " "  a = a * 3 + 4; " "  return a; }") == 40' failed: run_program("def int main() { " "  int a;" "  a = 2 + 3 * 4; " "  a = a - 4 / 2; " "  a = a * 3 + 4; " "  return a; }") == -9999, 40 == 40
public.c:31:F:Public:C_conditional:0: Assertion 'run_program("def int main() { " "  if (true) { return 2+1; } " "  else { return 3+1; } }") == 3' failed: run_program("def int main() { " "  if (true) { return 2+1; } " "  else { return 3+1; } }") == -9999, 3 == 3
public.c:36:F:Public:C_while:0: Assertion 'run_program("def int main() { " "  int a; a = 0; " "  while (a < 10) { a = a + 1; } " "  return a; }") == 10' failed: run_program("def int main() { " "  int a; a = 0; " "  while (a < 10) { a = a + 1; } " "  return a; }") == -9999, 10 == 10
public.c:42:F:Public:B_func_call:0: Assertion 'run_program("def int add(int a, int b) { return a + b; } " "def int main() { return add(2,3); }") == 5' failed: run_program("def int add(int a, int b) { return a + b; } " "def int main() { return add(2,3); }") == -9999, 5 == 5
public.c:46:F:Public:B_spilled_regs:0: Assertion 'run_program("def int main() { " "  return (((1+2)+(3+4))+((5+6)+(7+8)))+" "         (((1+2)+(3+4))+((5+6)+(7+8))); }") == 72' failed: run_program("def int main() { " "  return (((1+2)+(3+4))+((5+6)+(7+8)))+" "         (((1+2)+(3+4))+((5+6)+(7+8))); }") == -9999, 72 == 72
private.c:3:E:Private:A_null_insnlist:0: (after this point) Received signal 11 (Segmentation fault)
